### ISSUE TITLE
Sending number rather than string bug

### ISSUE THREAD

**Issue by Nabil-Alsaiad** [Doist/todoist-api-typescript#140]
## Bug description

The methods "TodoistApi.getSection()" and "TodoistApi.getProjectCollaborators()" are throwing a CONTENT_INCORRECT error.

- This is the one for the "TodoistApi.getProjectCollaborators()"

ValidationError: Validation failed:
{
  "id": "Expected string, but was number"
}.
Object should match { id: string; name: string; email: string; }
    at new ValidationError (...\node_modules\runtypes\lib\errors.js:22:28)
    at Object.check (...\node_modules\runtypes\lib\runtype.js:37:19)
    at validateUser (...\node_modules\@doist\todoist-api-typescript\dist\utils\validators.js:46:25)
    at Array.map (<anonymous>)
    at validateUserArray (...\node_modules\@doist\todoist-api-typescript\dist\utils\validators.js:50:18)
    at TodoistApi.<anonymous> (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:259:82)
    at step (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:33:23)
    at Object.next (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:14:53)
    at fulfilled (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'CONTENT_INCORRECT',
  details: { id: 'Expected string, but was number' }
}

- and this is the "TodoistApi.getSection()" one

ValidationError: Validation failed:
{
  "id": "Expected string, but was number",
  "projectId": "Expected string, but was number"
}.
Object should match { id: string; order: number; name: string; projectId: string; }
    at new ValidationError (...\node_modules\runtypes\lib\errors.js:22:28)
    at Object.check (...\node_modules\runtypes\lib\runtype.js:37:19)
    at TodoistApi.<anonymous> (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:287:80)
    at step (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:33:23)
    at Object.next (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:14:53)
    at fulfilled (...\node_modules\@doist\todoist-api-typescript\dist\TodoistApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'CONTENT_INCORRECT',
  details: {
    id: 'Expected string, but was number',
    projectId: 'Expected string, but was number'
  }
}

## Expected behaviour

I made sure that what I'm sending to the methods is of type string, so I think the todoist code somewhere is sending a number rather than a string to some other method

## Is reproducible

Yes, tried it more than once, still the same problem.

## To reproduce

Just make a new api and try running these methods with a valid string id

## Steps taken to try to reproduce

...

## Screenshots

...

## Version information:

-   Package version: 2.0.3

## Additional information

...

**Comment by henningmu** [comment]
@Nabil-Alsaiad thank you for bringing this to our attention. We can reproduce both issues and have forwarded the information to our API team to return the correct types. Once that's done, the SDK should work without any update. I'll let you know here when that's done 👍

**Comment by garyking** [comment]
Having this fixed would be great. At the moment, this package can't be used for accessing sections from Todoist.

**Comment by henningmu** [comment]
Hi folks (@garyking, @Nabil-Alsaiad),
Our API team has identified and resolved the issue. The SDK should work correctly now – no update needed 👍

**Comment by Nabil-Alsaiad** [comment]
Ok thanks 👍
