### ISSUE TITLE
Getting tasks with a filter returns 404

### ISSUE THREAD

**Issue by the-nick-wilson** [Doist/todoist-api-typescript#149]
## Bug description

In trying to call `.getTasks` with a filter, I'm getting a 404 error:

```
Error
    at file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17851:31
    at step (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17779:23)
    at Object.next (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17726:18)
    at file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17712:71
    at new Promise (<anonymous>)
    at __awaiter2 (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17694:14)
    at request2 (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:17846:14)
    at TodoistApi3.<anonymous> (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:18325:53)
    at step (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:18272:23)
    at Object.next (file:///Users/nicholaswilson/Developer/personal/todoist-helper-service/.sst/artifacts/dev-todoist-helper-service-MyStack-Cron-Job/services/functions/lambda.js:18219:18) {
  httpStatusCode: 404,
  responseData: '404 page not found\n',
  isAuthenticationError: [Function (anonymous)]
}
```

## Expected behaviour

Should return the tasks that the filter evaluates to.

## Is reproducible

Yes

## To reproduce

Add any sort of `filter` property to the `getTasks():

```
api.getTasks({filter: "#This Week*"})
        .then((tasks) => console.log(tasks))
        .catch((error) => console.log(error))
``` 

## Steps taken to try to reproduce

Removing the filter property causes the function to work, but returns all tasks.

## Screenshots

N/A - see error stack

## Version information:

-   Package version: 2.0.1

## Additional information

N/A

**Comment by hatappi** [comment]
I also faced the same issue. And also when I made a request using cURL, the same issue happened.

```console
➜ curl \
	-H "Content-Type: application/json" \
	-H "Authorization: Bearer $API_TOKEN" \
	"https://api.todoist.com/rest/v2/tasks?filter=tomorrow"
404 page not found
```

**Comment by the-nick-wilson** [comment]
> I also faced the same issue. And also when I made a request using cURL, the same issue happened.
> 
> ```
> ➜ curl \
> 	-H "Content-Type: application/json" \
> 	-H "Authorization: Bearer $API_TOKEN" \
> 	"https://api.todoist.com/rest/v2/tasks?filter=tomorrow"
> 404 page not found
> ```
> 
> Some filter works: `today`, `overdue`

`today` and `overdue` work, but `tomorrow` doesn't??

**Comment by henningmu** [comment]
Thank you for reporting this @the-nick-wilson and @hatappi, I can reproduce the problem. I have forwarded this to our API team and let you know once it's resolved 👍

**Comment by the-nick-wilson** [comment]
@henningmu - any progress from your API team on this one? Thanks!

**Comment by henningmu** [comment]
Hey folks (@the-nick-wilson @hatappi),
our API team has identified and resolved the issue. Using `getTasks` with any filter should work as expected now – no update to the SDK necessary.

Please feel free to reopen this issue if you're still experiencing issues and we're happy to look into them 👍

**Comment by the-nick-wilson** [comment]
> Hey folks (@the-nick-wilson @hatappi), our API team has identified and resolved the issue. Using `getTasks` with any filter should work as expected now – no update to the SDK necessary.
> 
> Please feel free to reopen this issue if you're still experiencing issues and we're happy to look into them 👍

thank you @henningmu - and Todoist API team!

**Comment by hatappi** [comment]
I also confirmed it worked well. Thank you!
